x-django-common:
  &django-common
  build:
    context: ./
    dockerfile: Dockerfile
  environment:
    - NUM_ARTICLES_TRAIN=1000
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - FLOWER_UNAUTHENTICATED_API=true
  volumes:
    - ./data:/app/data
    - static_data:/static
  networks:
    - django_network
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_data:/static
    ports:
      - 80:80
    networks:
      - django_network
    depends_on:
      - django

  django:
    <<: *django-common
    ports:
      - 8000
    entrypoint: /app/scripts/entrypoint.sh

  postgres:
    image: postgres:latest
    ports:
      - 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 5s
      retries: 5
    networks:
      - django_network

  redis:
    image: redis:alpine
    ports:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 5s
      retries: 5
    networks:
      - django_network

  celery_worker:
    <<: *django-common
    command: [ "/app/scripts/celery.sh", "celery" ]
    restart: always

  flower_worker:
    <<: *django-common
    command: [ "/app/scripts/celery.sh", "flower" ]
    restart: always
    ports:
      - 5555

volumes:
  pg_data:
  static_data:

networks:
  django_network:
    driver: bridge
