name: Deploy via YCR

on:
  push:
    tags:
      - 'v*.*.*'  # Триггер на теги v1.2.3

env:
  YC_REGISTRY: cr.yandex
  IMAGE_NAME: hello-world/cloud-hw-3
  FOLDER_ID: default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install yc CLI
        run: |
          curl -O https://storage.yandexcloud.net/yandexcloud-yc/release/yc_linux_386.tar.gz
          tar -xzf yc_linux_386.tar.gz
          chmod +x yc
          echo "$PWD" >> $GITHUB_PATH

      - name: Authenticate with Yandex Cloud
        run: |
          yc config set folder-id  ${{ env.FOLDER_ID }}
          yc config set token ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}

      - name: Log in to YCR
        run: |
          yc container registry configure-docker
          # Это добавит creds в ~/.docker/config.json

      - name: Build and push Docker image to YCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/Dockerfile
          push: true
          tags: |
            ${{ env.YC_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.YC_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            app_version=${{ env.VERSION }}
